In [1]:
import torch

torch.cuda.is_available()


True

In [2]:
if torch.cuda.is_available():  
  dev = "cuda:0" 
else:  
  dev = "cpu"  

In [3]:
device = torch.device(dev)  
a = torch.zeros(4,3)    
a = a.to(device)

In [4]:
torch.cuda.set_device(0)
dtype = torch.FloatTensor
dtype = torch.cuda.FloatTensor # Uncomment this to run on GPU
#cudnn.benchmark = True


In [4]:
print(torch.rand(2,3).cuda())

tensor([[0.4092, 0.7210, 0.9469],
        [0.6282, 0.8794, 0.4301]], device='cuda:0')


In [5]:
import tensorflow as tf
print(tf.config.experimental.list_physical_devices('GPU'))

[]


In [7]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

NameError: name 'net' is not defined

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [7]:
torch.cuda.current_device()

0

In [8]:
torch.cuda.device(0)

In [9]:
 torch.cuda.device_count()

1

In [10]:
torch.cuda.get_device_name(0)

'GeForce GT 750M'

In [11]:
# setting device on GPU if available, else CPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)
print()

#Additional Info when using cuda
if device.type == 'cuda':
    print(torch.cuda.get_device_name(0))
    print('Memory Usage:')
    print('Allocated:', round(torch.cuda.memory_allocated(0)/1024**3,1), 'GB')
    print('Cached:   ', round(torch.cuda.memory_cached(0)/1024**3,1), 'GB')

Using device: cuda

GeForce GT 750M
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB


In [12]:
torch.rand(1000).to(device)


tensor([0.3244, 0.1577, 0.1757, 0.9855, 0.3596, 0.9142, 0.2831, 0.9329, 0.2312,
        0.1245, 0.8279, 0.0640, 0.2826, 0.1068, 0.3222, 0.1630, 0.2270, 0.3112,
        0.5748, 0.6186, 0.7165, 0.2802, 0.9195, 0.8298, 0.3469, 0.2882, 0.9643,
        0.6968, 0.6768, 0.0928, 0.0061, 0.5333, 0.3340, 0.8205, 0.3186, 0.2719,
        0.9698, 0.1869, 0.1003, 0.4833, 0.3368, 0.8283, 0.4289, 0.3356, 0.1624,
        0.5723, 0.5441, 0.7492, 0.8340, 0.1056, 0.4510, 0.1722, 0.9147, 0.2724,
        0.0416, 0.7608, 0.6549, 0.5119, 0.4370, 0.4103, 0.1489, 0.5404, 0.0551,
        0.8925, 0.3806, 0.8141, 0.8987, 0.6562, 0.7613, 0.9101, 0.7337, 0.4132,
        0.7478, 0.1351, 0.7293, 0.6007, 0.0318, 0.0210, 0.0768, 0.4725, 0.7737,
        0.3090, 0.9714, 0.3350, 0.3148, 0.2548, 0.0826, 0.5997, 0.7538, 0.7937,
        0.1403, 0.1279, 0.6730, 0.6933, 0.8432, 0.2497, 0.4889, 0.8617, 0.4056,
        0.7780, 0.2732, 0.7698, 0.4049, 0.6898, 0.3120, 0.1949, 0.2766, 0.8021,
        0.0133, 0.0615, 0.4563, 0.6103, 

In [13]:
import numpy as np

class NeuralNetwork():
    
    def __init__(self):
        # seeding for random number generation
        np.random.seed(1)
        
        #converting weights to a 3 by 1 matrix with values from -1 to 1 and mean of 0
        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1

    def sigmoid(self, x):
        #applying the sigmoid function
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        #computing derivative to the Sigmoid function
        return x * (1 - x)

    def train(self, training_inputs, training_outputs, training_iterations):
        
        #training the model to make accurate predictions while adjusting weights continually
        for iteration in range(training_iterations):
            #siphon the training data via  the neuron
            output = self.think(training_inputs)

            #computing error rate for back-propagation
            error = training_outputs - output
            
            #performing weight adjustments
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))

            self.synaptic_weights += adjustments

    def think(self, inputs):
        #passing the inputs via the neuron to get output   
        #converting values to floats
        
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return output


if __name__ == "__main__":

    #initializing the neuron class
    neural_network = NeuralNetwork()

    print("Beginning Randomly Generated Weights: ")
    print(neural_network.synaptic_weights)

    #training data consisting of 4 examples--3 input values and 1 output
    training_inputs = np.array([[0,0,1],
                                [1,1,1],
                                [1,0,1],
                                [0,1,1]])

    training_outputs = np.array([[0,1,1,0]]).T

    #training taking place
    neural_network.train(training_inputs, training_outputs, 15000)

    print("Ending Weights After Training: ")
    print(neural_network.synaptic_weights)


Beginning Randomly Generated Weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Ending Weights After Training: 
[[10.08740896]
 [-0.20695366]
 [-4.83757835]]


In [15]:
# -*- coding: utf-8 -*-
import time
import torch
import math

start_time = time.time()
# your code

dtype = torch.float
device = torch.device("cpu")
#device = torch.device("cuda:0") # Uncomment this to run on GPU


for t in range(20000):

    # Randomly initialize weights
    a = torch.randn((), device=device, dtype=dtype)
    b = torch.randn((), device=device, dtype=dtype)
    c = torch.randn((), device=device, dtype=dtype)
    d = torch.randn((), device=device, dtype=dtype)



elapsed_time = time.time() - start_time
print("elapsed time", elapsed_time)
print(f'Result: y = {a.item()} + {b.item()} x + {c.item()} x^2 + {d.item()} x^3')

elapsed time 0.6828737258911133
Result: y = -0.2790149450302124 + -1.331552267074585 x + 1.7954853773117065 x^2 + -1.4032344818115234 x^3


In [18]:
import numpy, random, os
lr = 1 #learning rate
bias = 1 #value of bias
weights = [random.random(),random.random(),random.random()] #weights generated in a list (3 weights in total for 2 neurons and the bias)

In [19]:
def Perceptron(input1, input2, output) :
   outputP = input1*weights[0]+input2*weights[1]+bias*weights[2]
   if outputP > 0 : #activation function (here Heaviside)
      outputP = 1
   else :
      outputP = 0
   error = output - outputP
   weights[0] += error * input1 * lr
   weights[1] += error * input2 * lr
   weights[2] += error * bias * lr

In [20]:
for i in range(50) :
   Perceptron(1,1,1) #True or true
   Perceptron(1,0,1) #True or false
   Perceptron(0,1,1) #False or true
   Perceptron(0,0,0) #False or false

In [21]:
x = int(input())
y = int(input())
outputP = x*weights[0] + y*weights[1] + bias*weights[2]
if outputP > 0 : #activation function
   outputP = 1
else :
   outputP = 0
print(x, "or", y, "is : ", outputP)

ValueError: invalid literal for int() with base 10: ''

In [11]:
outputP = 1/(1+numpy.exp(-outputP)) #sigmoid function


In [12]:
print(outputP)

0.6750375273768237
